# This is a basic workflow to help you get started with Actions

name: DataFactory

# Controls when the workflow will run
on:
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Install Data Factory Libary
        run: npm install
        working-directory: ${{ github.workspace }}/DataFactory/src
        
      - name: Validate Data Factory
        run: npm run build validate ${{ github.workspace }}/DataFactory/src /subscriptions/{redacted}/resourceGroups/rg-workshops-datafactory-dev/providers/Microsoft.DataFactory/factories/df-hs-workshop-dev
        working-directory: ${{ github.workspace }}/DataFactory/src
      
      - name: Build Data Factory Arm Template
        run: npm run build export ${{ github.workspace }}/DataFactory/src /subscriptions/{redacted}/resourceGroups/rg-workshops-datafactory-dev/providers/Microsoft.DataFactory/factories/df-hs-workshop-dev "ArmTemplate"
        working-directory: ${{ github.workspace }}/DataFactory/src
      
      - name: Upload Data factory arm template
        uses: actions/upload-artifact@v2.2.4
        with:
          name: DataFactoryArm
          path:  ${{ github.workspace }}/DataFactory/src/ArmTemplate
          if-no-files-found: error
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.0.10
      with:
        name: DataFactoryArm
        path: ${{ github.workspace }}/ArmTemplate
    - name: Login to Azure
      uses: azure/login@v1
      with: 
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Release
      uses: azure/arm-deploy@v1
      with: 
        resourceGroupName: 'rg-workshops-datafactory-qa'
        template: ${{ github.workspace }}/ArmTemplate/ARMTemplateForFactory.json
        parameters: factoryName=df-hs-workshop-qa AzureBlobStorage1_connectionString=${{secrets.AZURE_STORAGECONNECTIONSTRING}}
